version: "3"

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - /docker/gitea/data:/data
      - /docker/gitea/custom:/app/gitea/custom
      - /docker/gitea/log:/app/gitea/log
    ports:
      - "3000:3000"
      - "2222:22"
